# SPDX-FileCopyrightText: None
#
# SPDX-License-Identifier: CC0-1.0

name = "markov-chain-notestock"
compatibility_date = "2025-10-03"

[assets]
directory = "./wasm/public"
not_found_handling = "404-page"
