# SPDX-FileCopyrightText: None
#
# SPDX-License-Identifier: CC0-1.0

[target.wasm32-unknown-unknown]
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1
